// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cognito_identity_pool_id: 'us-east-2:42fb2ebf-6bd7-4d54-bc45-f4c8bed24f4c',
  aws_cognito_region: 'us-east-2',
  aws_content_delivery: 'enable',
  aws_content_delivery_bucket: 'mommymonitor-hosting-mobilehub-470597825',
  aws_content_delivery_bucket_region: 'us-east-2',
  aws_content_delivery_cloudfront: 'enable',
  aws_content_delivery_cloudfront_domain: 'd10ds450cz0zjw.cloudfront.net',
  aws_mobile_analytics_app_id: 'a37d31e6fb5d4cb2905defdf513e1bd3',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: '230fb217-88af-458c-ac74-b0c91e54c1af',
  aws_project_name: 'MommyMonitor',
  aws_project_region: 'us-east-2',
  aws_resource_name_prefix: 'mommymonitor-mobilehub-470597825'
};

export default awsmobile;
